import Head from "next/head";

import {
  AboutUs,
  MainText,
  ServicesOffer,
  ourClients,
  ourDentists,
  ourMilestones,
} from "@/Data/ProjectData";
import MainServiceComp from "@/components/InfoSection/Services/MainServiceComp";
import Milestones from "@/components/CountUpComp/Milestones";
import styles from "../styles/styles.module.scss";
import Dentists from "@/components/InfoSection/OurDentists/Dentists";
import CarouselSection from "@/components/Banner/Carousel";
import About from "./about";
import DentistsText from "@/components/InfoSection/OurDentists/DentistsText";
import ReviewSection from "@/components/InfoSection/Reviews/ReviewSection";
// import Home from '../styles/Home.module.scss'
export type THome = {
  textScroll: typeof MainText;
  miles: typeof ourMilestones;
  dataDentists: typeof ourDentists;
  offers: typeof ServicesOffer;
  ourClients: typeof ourClients;
};
export default function Home({
  textScroll,
  miles,
  dataDentists,
  offers,
  ourClients,
}: THome) {
  const serviceTitle = offers.map((offer) => offer.title);
  return (
    <>
      <Head>
        <title>Vesna-Dent</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/some-dental-logo.png" />
      </Head>
      <CarouselSection {...textScroll} />
      <div className={styles.container}>
        <div className={styles.MainImagesContainer}>
          {dataDentists.map((dentistData) => (
            <Dentists key={dentistData.id} {...dentistData} />
          ))}
        </div>
        <div className={styles.textSection}>
          <DentistsText {...AboutUs} />
        </div>
      </div>
      <MainServiceComp title={serviceTitle} id={0} />
      <ReviewSection reviewcards={ourClients} />
      <div className={styles.Milestones}>
        {miles.map((mileItem) => (
          <Milestones key={mileItem.id} {...mileItem} />
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  return {
    props: {
      textScroll: MainText,
      miles: ourMilestones,
      dataDentists: ourDentists,
      offers: ServicesOffer,
      ourClients: ourClients,
    },
  };
}
